fnet:
  model: original
  TrainingDataSize: 1000000
  TestingDataSize: 5000
  IsParallel: false
  EpochNum: 2001
  TestInterval: 20
  BatchSize: 500000
  lr: 1.0e-3
  lr_decay_step: 200
  lr_decay_gamma: 0.9
  TrainDataPath: ./data/coatings/L30_R5.0_T10-400_1M.mat
  TestDataPath: ./data/coatings/L30_R5.0_T10-400_50K.mat
  StartWL: 400
  EndWL: 1005
  Resolution: 5
  params_min: 10
  params_max: 400
PCSED:
  TrainingDataSize: 1000000
  TestingDataSize: 10000
  IsParallel: false
  EpochNum: 501
  TestInterval: 1
  BatchSize: 100000
  lr: 1.0e-4
  params_lr_coef: 1.0e+4
  lr_decay_step: 50
  lr_decay_gamma: 0.8
  beta_range: 1.0e-3
  TFNum: 9
  #override_filters: ./nets/hybnet/202031027_104727
  QEC: ./data/QEC.mat
  fnet_folder: ./nets/fnet/TMM_L20_R5.0
  TrainDataPath: ./data/ICVL_400-1000-5_1M.mat
  TestDataPath: ./data/ICVL_400-1000-5_100K.mat
  History: true
  ADMM_net: ./nets/ADMM_net/20240125_220605/admm_net.pkl
noise:
  SNR: 60
  alpha: 0.
  dc: 0
  bitdepth: 8
